dependencies:
- name: aggregationinterval
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.73
- name: anipet
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.152
- name: daka90
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: dental
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.160
- name: dr-gav
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.23
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: instax
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: joyday
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: mandiri-syariah
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: monday
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.79
- name: optica-halperin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.64
- name: persona-decide-helper
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: ribbedtee
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.54
- name: saas
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.161
- name: saas-server
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.67
- name: select
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.269
- name: selectmedia
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.279
- name: terminalx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.40
- name: z-crave
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.204
