dependencies:
- name: aggregationinterval
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.63
- name: anipet
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.100
- name: dental
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.140
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: monday
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.77
- name: optica-halperin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.35
- name: persona-decide-helper
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: ribbedtee
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: saas
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.152
- name: saas-server
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.59
- name: terminalx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- name: z-crave
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.126
