dependencies:
- name: aggregationinterval
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.53
- name: anipet
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.75
- name: dental
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.130
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: monday
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.74
- name: saas-server
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.57
- name: z-crave
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.111
