dependencies:
- name: aggregationinterval
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.55
- name: anipet
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.93
- name: dental
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.135
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: monday
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.77
- name: optica-halperin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.33
- name: saas
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.150
- name: saas-server
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.57
- name: terminalx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- name: z-crave
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.120
