dependencies:
- name: aggregationinterval
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.65
- name: anipet
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.145
- name: dental
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.155
- name: dr-gav
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.20
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: monday
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.79
- name: optica-halperin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.60
- name: persona-decide-helper
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.6
- name: ribbedtee
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.50
- name: saas
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.156
- name: saas-server
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.63
- name: select
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.249
- name: terminalx
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.37
- name: z-crave
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.194
