PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: null
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    #helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: comvert.io
    exposer: Ingress
    http: "false"
    tls-acme: "true"
jenkins:
  Servers:
    Global: {}
  enabled: null
prow: {}
